# These are supported funding model platforms

github: [getify]
patreon: getify
custom: ['https://www.paypal.com/paypalme2/getify','https://explorer.hiro.so/address/SPFBP27YQAR2DRNXNTC7X4MQV9EZXG0RQGXGNNFR?chain=mainnet']
